/triton/controls/thrust_allocator:
  ros__parameters:
      # Thrusters will follow the following naming convention: 

#                            __
#                           |  |Thruster 4 ___
#                       ____|__|__________|___| Thruster 3 (angled)
#                       |                 |
#                  _____|       +y        |
#              ___|╭───╮       |          |_
# Thruster 6  |___|│ 5 │       |___+x     |_) AUV front 
#                 |╰───╯       +z         |
#                  ‾‾‾‾‾|  (pointing up)  |
#                       |_________________|___
#                           |  |          |___| Thruster 2 (angled)
#                           |__|Thruster 1

    num_thrusters: 6
    bits_per_thruster: 5
    max_fwd: 3.71 # kgf
    max_rev: 2.92 # kgf
    t1:
      contrib:
        x: -1.0
      lx: -0.175
      ly: -0.3275
      lz: 0.0
    t2:
      contrib:
        y: -0.7071
        z: -0.7071
      help:
        x: -0.028
      lx: 0.45  
      ly: -0.2145
      lz: -0.0085
    t3:
      contrib:
        y: 0.7071
        z: -0.7071
      help:
        x: -0.028
      lx: 0.45
      ly: 0.2145
      lz: -0.0085
    t4:
      contrib:
        x: -1.0
      lx: -0.175
      ly: 0.3275
      lz: 0.0
    t5:
      contrib:
        z: -1.0
      lx: -0.319431
      ly: 0.0
      lz: 0.08
    t6:
      contrib:
        y: -1.0
      lx: -0.455 
      ly: 0.0
      lz: 0.0
    

    
    
    
