/triton/controls/thrust_allocator:
  ros__parameters:
  # Old values are commented, we should think about remodelling the Gazebo Sim to match
  #
  #       # Thrusters will follow the following naming convention: 

      #               ___      Thruster 1
      #    Thruster 3 ___________|__|________
      #                 |                    |
      #                 |        -x          |
      #            Thruster 5 |||            |_
      #                 |     |||___+y       |_) AUV front 
      #                 |     +z             |
      #                 |   (pointing up)    |
      #               __|____________________|   
      #    Thruster 4 ___        |  |        
      #                        Thruster 2

    num_thrusters: 6
    bits_per_thruster: 5
    max_fwd: 3.71 # kgf
    max_rev: 2.92 # kgf
    t5:
      contrib:
        y: -1.0
      lx: -0.3284
      ly: -0.075
      lz: 0.0
    t6:
      contrib:
        y: -1.0
      lx: 0.3284
      ly: -0.075
      lz: 0.0
