/steelhead/pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - steelhead_example::ComponentOne
        - steelhead_example::ComponentTwo
      pkg_names: 
        - steelhead_example
        - steelhead_example
      param_files:
        - ''
        - params_two.yaml
      namespace: /steelhead
      remap_rules:
        - /steelhead/example/component_two/in:=/steelhead/example/component_one/out
    use_sim_time: false

