/steelhead/pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - steelhead_tasks::PitchFlip
      pkg_names:
        - steelhead_tasks
      param_files:
        - pitch_flip.yaml
      namespace: /steelhead
      remap_rules:
        - ''
    use_sim_time: false
