/steelhead/pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - steelhead_tasks::HardcodeInputs
      pkg_names:
        - steelhead_tasks
      param_files:
        - navigate_backwards.yaml
      namespace: /steelhead
      remap_rules:
        - ''
    use_sim_time: false
