pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - steelhead_controls::WaypointMarker
      pkg_names:
        - steelhead_controls
      namespace: /steelhead/waypoint
    use_sim_time: false
