version: "2"

services:
  micro-ros:
    image: microros/micro-ros-agent:foxy
    privileged: true
    command: serial --dev /dev/ttyACM0 # /dev/ttyACM0 is the expected location of the teensy, if this is not the case, this values must be changed
    volumes:
      - "/dev:/dev"
    network_mode: "host"
  ros: 
    image: ubcsubbots/steelhead:latest
    privileged: true
    command: ros2 launch steelhead_pipeline pipeline_launch.py sequence:=example_sequence.yaml
    volumes:
      - "/dev:/dev"
    network_mode: "host"
