# Available pipeline types
string TYPE_EXAMPLE = "example"
string TYPE_WAYPOINT_MARKER = "waypoint_marker"
string TYPE_GATE_SEARCH = "task_gate_search"
string TYPE_GATE_APPROACH = "task_gate_approach"
string TYPE_GATE_YOLO = "task_gate_yolo"
string TYPE_GATE_DONE = "task_gate_done"
string TYPE_FORWARD_DRIVE = "competition_task_forward"
string TYPE_UPWARD_DRIVE = "competition_task_upward"
string TYPE_STYLE_SPIN = "competition_task_style"

# type must be one of the above pipeline types (i.e "circle_approach")
string type
