pipeline_manager:
  ros__parameters:
    pipeline:
      components:
      - circle_approach::CircleDetector
      - circle_approach::CirclePoseEstimator
      namespace: /tr/circle_approach
      pkg_name: tr_circle_approach
      remap_rules:
      # - /tr/circle_approach/detector/in:=/tr/drivers/camera/front/image_rect
        - /tr/circle_approach/detector/in:=/tr/gazebo_drivers/camera/front/image_raw
        - /tr/circle_approach/pose_estimator/point:=/tr/gazebo_controller/input
    use_sim_time: false
