name: ROS2 Build and Test CI

on:
  push:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-26.04
    container:
      image: hashaam1217/subbots_steelhead_testing:1.0.1
    steps:
      - name: Ensure Permissions
        run: |
          sudo mkdir -p /__w/_temp
          sudo mkdir -p /__w/_actions
          sudo chmod -R 777 /__w/_temp
          sudo chmod -R 777 /__w/_actions

      # Cleaning up disk space
      - name: Clean up disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /var/cache/apt/*
          sudo rm -rf /usr/share/man/?? 
          sudo rm -rf /usr/share/man/??_*
          sudo rm -rf /var/tmp/*
          sudo rm -rf /tmp/*

      - name: Update and upgrade
        run: |    
          sudo apt update -y
          sudo apt upgrade -y

      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2604/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda libcudnn9-cuda-13 libcudnn9-dev-cuda-13

      - name: Set CUDA paths
        run: |
          echo "/usr/local/cuda/lib64" >> $GITHUB_PATH
          echo "/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Check out ubc-subbots/steelhead
        uses: actions/checkout@v3  # Update to the latest version.

      - name: Install deps with rosdep
        run: |
          rosdep init
          rosdep update
          PIP_BREAK_SYSTEM_PACKAGES=1 rosdep install -i --from-path src --rosdistro lyrical -y


      - name: Source setup and build then test using colcon
        shell: bash
        env:
          Torch_DIR: ${{ github.workspace }}/libtorch/libtorch/share/cmake/Torch
        run: |
          source /opt/ros/lyrical/setup.bash
          colcon build --cmake-args -DCMAKE_CXX_STANDARD=20 -DTorch_DIR=$Torch_DIR
          source ./install/setup.bash
          colcon test
          colcon test-result --verbose
